### ISSUE TITLE
HLD

### ISSUE THREAD

**Issue by yyujinjj** [yyujinjj/GreenScan#5]
HLD

**Comment by KimTaekgyoon** [comment]
[프로젝트_설계서(HLD)_그린스캔 (2.1).pdf](https://github.com/yyujinjj/GreenScan/files/15067099/_.HLD._.2.1.pdf)

**Comment by KimTaekgyoon** [comment]
[프로젝트_설계서(HLD)_그린스캔.pdf](https://github.com/yyujinjj/GreenScan/files/15078326/_.HLD._.pdf)
