### ISSUE TITLE
Name for argument of type [java.lang.String] not specified, and parameter name information not available via reflection.

### ISSUE THREAD

**Issue by friendship-jung** [yyujinjj/GreenScan#85]
게시판 만들기를 하는 과정에서 title과 content를 입력하는 과정에서, 입력을 한 결과가  
@PostMapping("/board/writepro")
    public String boardWritePro(String title, String content){

        System.out.println("제목 :" + title);
        System.out.println("내용 :" + content);

        return "";
    }
코드에 의해 intelli j에 출력창에 나타나야되는 데 제목과 같은 오류가 나타나고, 구글링을 통한 여러 방법을 도입해보고 하였지만 실패하였다.

**Comment by pilsungk-oss** [comment]
@friendship-jung 
에러 메시지 정보 필요

**Comment by pilsungk-oss** [comment]
@friendship-jung 
아래 내용 참고
컴파일 시점에 -parameters 옵션 줘 봤는지?

![image](https://github.com/yyujinjj/GreenScan/assets/49965974/de53d758-06eb-4117-b527-a840d5e5ab17)

**Comment by friendship-jung** [comment]
![image](https://github.com/yyujinjj/GreenScan/assets/165870307/9cef0abd-14ba-4d4d-a02e-22c6e608c755)
코드를 수정하고 코드만 수정하였을때 분명히 되지 않았다가 java를  갈아서 다시 설정하여 되었습니다.
